extends:
  - stylelint-config-standard

overrides:
  - files:
      - '**/*.css'
    customSyntax: postcss

  - files:
      - '**/*.scss'
    customSyntax: postcss-scss

rules:
  no-duplicate-selectors: true
  color-hex-length: long
  color-named: never
  selector-no-qualifying-type:
  - true
  - ignore: ["attribute", "class", "id"]
  selector-max-id: 1
  selector-attribute-quotes: always
  declaration-no-important: true
  property-no-vendor-prefix: true
  value-no-vendor-prefix: true
  function-url-quotes: always
  font-weight-notation: numeric
  font-family-name-quotes: always-where-recommended
  comment-whitespace-inside: always
  comment-empty-line-before: always
  at-rule-no-vendor-prefix: true
  rule-empty-line-before:
  - always
  - ignore: ["after-comment", "first-nested", "inside-block"]
  selector-pseudo-element-colon-notation: double
  selector-no-vendor-prefix: true
  media-feature-name-no-vendor-prefix: true
  scss/dollar-variable-empty-line-before: null
