name: Continuous integration

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

env:
  NODE: 18

jobs:
  install:
    name: Build and start Node.js project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: '${{ env.NODE }}'

      - name: Install dependencies in the project
        run: npm ci

      - name: Build the project
        run: npm run build

  jest-unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: '${{ env.NODE }}'

      - name: Install dependencies in the project
        run: npm ci

      - name: Run unit tests using Jest
        run: npm run jest:run

  cypress-components:
    name: Run component tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: '${{ env.NODE }}'

      - name: Install dependencies in the project
        run: npm ci

      - name: Run Cypress verification
        run: npm run cy:verify

      - name: Run component tests using Cypress
        run: npm run cy:component:headless

  cypress-e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: '${{ env.NODE }}'

      - name: Install dependencies in the project
        run: npm ci

      - name: Run Cypress verification
        run: npm run cy:verify

      - name: Run E2E tests using Cypress
        run: npm run cy:e2e:headless
