name: Run tests using Jest

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  jest-unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - "18"

    steps:
    - name: Checkout the current branch
      uses: actions/checkout@main

    - name: Set up Node.js
      uses: actions/setup-node@main
      with:
        node-version: '${{ matrix.node-version }}'

    - name: Cache dependencies installed with Node Package Manager
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node_modules-${{hashFiles('package-lock.json')}}
        restore-keys: node_modules-

    - name: Install dependencies in the project
      run: npm ci

    - name: Build the project
      run: npm run build

    - name: Run unit tests using Jest
      run: npm run jest:run
